name: Deploy Storybook
on:
    workflow_dispatch:

permissions:
  id-token: write # OIDC
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/composites/setup
        with:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Storybook
        run: pnpm turbo run build:storybook

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Upload storybook-static to S3
        working-directory: ./apps/storybook
        run: |
          aws s3 sync storybook-static s3://${{ secrets.STORYBOOK_STATIC_S3_BUCKET }} \
            --delete

      - name: Invalidate CloudFront cache
        run: |
            aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.STORYBOOK_STATIC_CLOUDFRONT_ID }} \
            --paths "/*"
